import React from "react";

export default function InsightsDisclaimerCard() {
  return (
    <article className="w-full rounded-[16px] border border-[#BFDBFE] bg-gradient-to-r from-[#EFF6FF] to-[#EEF2FF] p-6 shadow-[0_1px_3px_0_rgba(0,0,0,0.1),0_1px_2px_-1px_rgba(0,0,0,0.1)]">
      <div className="flex gap-4">
        <div className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#DBEAFE]">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            aria-hidden="true"
          >
            <g clipPath="url(#clip0_8693_4213)">
              <path
                d="M7.99992 14.6667C11.6818 14.6667 14.6666 11.6819 14.6666 8.00004C14.6666 4.31814 11.6818 1.33337 7.99992 1.33337C4.31802 1.33337 1.33325 4.31814 1.33325 8.00004C1.33325 11.6819 4.31802 14.6667 7.99992 14.6667Z"
                stroke="#2563EB"
                strokeWidth="1.33333"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M8 5.33337V8.00004"
                stroke="#2563EB"
                strokeWidth="1.33333"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M8 10.6666H8.00667"
                stroke="#2563EB"
                strokeWidth="1.33333"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </g>
            <defs>
              <clipPath id="clip0_8693_4213">
                <rect width="16" height="16" fill="white" />
              </clipPath>
            </defs>
          </svg>
        </div>

        <div className="flex flex-1 flex-col gap-2">
          <p
            className="text-[#1E3A8A] text-xs font-semibold leading-4"
            style={{ fontFamily: "Montserrat" }}
          >
            AI-Generated Insights Disclaimer
          </p>
          <p
            className="text-[#1E40AF] text-xs leading-5"
            style={{ fontFamily: '"Source Code Pro"' }}
          >
            These insights are automatically generated by AI based on
            statistical analysis of the dataset. While we strive for accuracy,
            please verify critical findings with source data. This system
            analyzes trends and patterns but does not make individual-level
            predictions or recommendations.
          </p>
          <p
            className="text-[#1E40AF] text-xs leading-5"
            style={{ fontFamily: '"Source Code Pro"' }}
          >
            Privacy: Analysis runs on your dataset only. Your data is not used
            for AI training, not shared with third parties, and not stored
            beyond this session. Not intended for collecting PII or sensitive
            data.
          </p>
        </div>
      </div>
    </article>
  );
}
